### ISSUE TITLE
'webpack' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by senthil-k8s** [balaji-sivasakthi/leadgen-widget#11]
### Description
When trying to use the 'webpack' command in the terminal, I'm getting the error "'webpack' is not recognized as an internal or external command". I have already installed Node.js, but the issue persists.

### Expected Behavior
Webpack should run without any errors.

### Environment
- Operating System: Windows 10
- Node.js Version: 14.17.6

**Comment by balaji-sivasakthi** [comment]
install `webpack-cli` globally
